name: check
on: push
jobs: 
    check_if_formatted: 
        name: check if formatted
        runs-on: ubuntu-18.04
        steps:
          - run: sudo apt-get update
          - name: install clang-format
            run: sudo apt-get install clang-6.0
          - run: ls -la
          - used: actions/checkout@v1.0.0
          - run: ls -la
          - name: execute format.sh
            run: ./check_format.sh