name: check
on: push
jobs:
    check_format: 
        name: check format
        runs-on: ubuntu-18.04
        steps:
          - uses: actions/checkout@v1.0.0
          - run: echo deb http://archive.ubuntu.com/ubuntu bionic main restricted universe multiverse > /etc/apt/sources.list
          - run: echo deb http://archive.ubuntu.com/ubuntu bionic-security main restricted universe multiverse >> /etc/apt/sources.list
          - run: echo deb http://archive.ubuntu.com/ubuntu bionic-updates main restricted universe multiverse >> /etc/apt/sources.list
          - run: sudo apt-get update
          - run: sudo apt-get upgrade
          - run: sudo apt-get install clang-format
          - run: clang-format --version
          - run: script/check_format.sh
    compile:
        name: compile
        runs-on: ubuntu-18.04
        steps:
          - uses: actions/checkout@v1.0.0
          - run: g++ --version
          - run: script/compile.sh
            