name: check
on: push
jobs: 
    check_format: 
        name: check format
        runs-on: ubuntu-18.04
        steps:
          - name: checkout
            uses: actions/checkout@v1.0.0
          - name: apt update
            run: sudo apt-get update
          - name: install clang
            run: sudo apt-get install clang-6.0
          - name: execute format.sh
            run: ./check_format.sh