name: check
on: push
jobs:
    check_format: 
        name: check format
        runs-on: ubuntu-18.04
        steps:
          - uses: actions/checkout@v1.0.0
          - run: sudo apt remove -y clang-6.0 libclang-common-6.0-dev libclang1-6.0 libllvm6.0
          - run: sudo apt autoremove
          - run: sudo apt update
          - run: sudo apt install -f clang-format
          - run: clang-format --version
          - run: script/check_format.sh
    compile:
        name: compile
        runs-on: ubuntu-18.04
        steps:
          - uses: actions/checkout@v1.0.0
          - run: g++ --version
          - run: script/compile.sh
            