name: check
on: push
jobs: 
    checkout:
        name: checkout repository
        runs-on: ubuntu-18.04
        steps:
          - uses: actions/checkout@v1.0.0
    apt_update:
        name: apt update
        steps:
          - run: sudo apt-get update
    install_clang:
        name: install clang-format
        needs: apt_update
        steps:
          - run: sudo apt-get install clang-6.0
    check_if_formatted: 
        name: check if formatted
        runs-on: ubuntu-18.04
        needs: install_clang
        steps:
          - name: execute format.sh
            run: ./check_format.sh